{
 "title": "Netatmo Weather Station",
 "tags": [
  "netatmo",
  "weather"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "home",
    "label": "Home",
    "query": {
     "query": "label_values(netatmo_station_reachable,home)"
    }
   },
   {
    "name": "station",
    "label": "Station",
    "query": {
     "query": "label_values(netatmo_station_reachable,station)"
    }
   },
   {
    "name": "temperature_module",
    "label": "Temperature Module",
    "query": {
     "query": "label_values(netatmo_temperature{type=~\"NAMain|NAModule1|NAModule4\"},module)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Module Details $temperature_module",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_temperature{station=\"$station\", module=\"$module\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_humidity{station=\"$station\", module=\"$module\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 2, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "netatmo_rf_status{station=\"$station\", module=\"$module\"} * -1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Battery",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 2, "x": 22, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_battery_percent{station=\"$station\", module=\"$module\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "netatmo_temperature{station=\"$station\", module=\"$module\"}",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(netatmo_temperature{station=\"$station\", module=\"$module\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "netatmo_humidity{station=\"$station\", module=\"$module\"}",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Min:",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "min(netatmo_humidity{station=\"$station\", module=\"$module\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg:",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(netatmo_temperature{station=\"$station\", module=\"$module\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg:",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(netatmo_humidity{station=\"$station\", module=\"$module\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "min(netatmo_temperature{station=\"$station\", module=\"$module\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max:",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(netatmo_humidity{station=\"$station\", module=\"$module\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Station",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"min-height:200px; display:flex; justify-content:center; align-items:center;\">\n    <h1 style=\"font-size:300%; font-weight:bold;\">🏠 $home</h1>\n</div>\n"
   }
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "netatmo_noise{home=\"$home\",station=\"$station\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Noise Level",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_noise{home=\"$home\",station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "expr": "netatmo_pressure{home=\"$home\",station=\"$station\"}",
     "legendFormat": "{{station}}"
    }
   ]
  },
  {
   "title": "Pressure Trend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_pressure_trend{home=\"$home\",station=\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_temperature{home=\"$home\",station=\"$station\",type=\"NAModule1\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Temperature Trend",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_temperature_trend{home=\"$home\",station=\"$station\",type=\"NAModule1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "netatmo_humidity{home=\"$home\",station=\"$station\",type=\"NAModule1\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_humidity{home=\"$home\",station=\"$station\",type=\"NAModule1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timezone",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_station_reachable{home=\"$home\",station=\"$station\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "timezone",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_station_altitude{home=\"$home\",station=\"$station\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "altitude",
     "query": "from(bucket: \"netatmo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"station\"] == \"${station}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"altitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=~", "value": "/^$Station$/" }
     ]
    }
   ]
  },
  { "title": "All Indoor Modules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_temperature{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_temperature{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Min:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(netatmo_temperature{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Avg:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(netatmo_temperature{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Max:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(netatmo_temperature{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "netatmo_co2{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_co2{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Min:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(netatmo_co2{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Avg:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(netatmo_co2{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Max:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(netatmo_co2{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "netatmo_humidity{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_humidity{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"}",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Min:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(netatmo_humidity{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Avg:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(netatmo_humidity{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Max:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(netatmo_humidity{home=\"$home\",station=\"$station\",type=~\"NAMain|NAModule4\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "rain_module",
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "mm" } },
     "targets": [
      {
       "expr": "netatmo_rain{home=\"$home\",station=\"$station\",type=\"NAModule3\"}",
       "legendFormat": "{{station}}"
      }
     ]
    },
    {
     "title": "Summary (Last Hour)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "suffix: mm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_rain_1h{home=\"$home\",station=\"$station\",type=\"NAModule3\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "netatmo_rf_status{home=\"$home\",station=\"$station\",type=\"NAModule3\"} * -1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Summary (Today)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "suffix: mm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_rain_24h{station=\"$station\", type=\"NAModule3\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Battery",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_battery_percent{home=\"$home\",station=\"$station\",type=\"NAModule3\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "wind_module",
   "collapsed": true,
   "panels": [
    {
     "title": "Wind",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "expr": "netatmo_wind_strength{home=\"$home\",station=\"$station\",type=\"NAModule2\"}",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Wind Angle",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 7, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_wind_angle{home=\"$home\",station=\"$station\",type=\"NAModule2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gust",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "expr": "netatmo_gust_strength{home=\"$home\",station=\"$station\",type=\"NAModule2\"}",
       "legendFormat": "{{module}}"
      }
     ]
    },
    {
     "title": "Gust Angle",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_gust_angle{home=\"$home\",station=\"$station\",type=\"NAModule2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signal",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "netatmo_rf_status{home=\"$home\",station=\"$station\",type=\"NAModule2\"} * -1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Battery",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netatmo_battery_percent{home=\"$home\",station=\"$station\",type=\"NAModule2\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}